sudo: required

language: go

services:
  - docker

go:
- 1.8.x
- 1.9.x
- 1.10.x

before_install:
  - go get -v -d -t github.com/dingdayu/md5x

install:
  - go build .
  - ./md5x -dir $HOME

script:
  - docker build -t dingdayu/md5x .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dingdayu/md5x