sudo: required

language: go

services:
  - docker

go:
- 1.8.x
- 1.9.x
- 1.10.x

before_install:
  - go get -v -d -t github.com/dingdayu/md5x

install:
  - go build .
  - ./md5x -dir $HOME

script:
  - docker build -t dingdayu/md5x .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push dingdayu/md5x